services:
  db:
    image: postgres:13
    ports:
      - ${DB_BIND}:5432
    environment:
      POSTGRES_USER: template_user
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: template_database
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:5.0.3
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - ${REDIS_BIND}:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redisdata:/data

volumes:
  db_data:
  redisdata: