services:
  db:
    image: postgres:13
    ports:
      - ${DB_BIND}:5432
    environment:
      POSTGRES_USER: template_user
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: template_database
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:6
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - ${REDIS_BIND}:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
  plantuml-server:
    build:
      context: .
      dockerfile: ./plantuml-server/Dockerfile
    ports:
      - ${PLANTUML_BIND}:8080

volumes:
  db_data:
  redis_data: